"""User model update

Revision ID: 4f958eb3a908
Revises: 330210ab1844
Create Date: 2025-03-08 00:01:23.511433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f958eb3a908'
down_revision: Union[str, None] = '330210ab1844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_index('ix_users_account_id', table_name='users')
    op.drop_index('ix_users_oauth_name', table_name='users')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'oauth_name')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'expires_at')
    op.drop_column('users', 'account_id')
    op.drop_column('users', 'account_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('account_id', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('oauth_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.create_index('ix_users_oauth_name', 'users', ['oauth_name'], unique=False)
    op.create_index('ix_users_account_id', 'users', ['account_id'], unique=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
